

---LEFT OUTER JOİN:RETURNS THE MATCHİNG RECORDS, AND LEFT TABLE NONE MATCHİNG RECORDS

select * from EMPLOYEES E LEFT OUTER JOIN  ADDRESS A ON E.EMPLOYEE_ID=A.ADDRESS_ID;

select EMPLOYEE_ID,first_name,last_name,address,PHONE
from EMPLOYEES left outer join ADDRESS
on EMPLOYEES.EMPLOYEE_ID =ADDRESS.ADDRESS_ID;


--LEFT OUTER JOİN WİTH WHERE :RETURNS THE NONE MATCHİNG RECORDS FROM LEFT TABŞE
select EMPLOYEE_ID,first_name,last_name,address,PHONE
from EMPLOYEES left outer join ADDRESS
on EMPLOYEES.EMPLOYEE_ID =ADDRESS.ADDRESS_ID WHERE EMPLOYEES.EMPLOYEE_ID is null ;
